import Producto, { Categoria, Talle } from '@/types/producto.class';

export default async function ProductosGet() {
  // FIXME: return (await axios.get('/productos')).data;
  await new Promise((resolve) => setTimeout(resolve, 1500));
  return [
    new Producto({
      idProducto: 1,
      idProveedor: 101,
      nombre: 'Camiseta básica',
      descripcion: 'Camiseta de algodón 100%',
      precioVenta: 25.5,
      precioCompra: 15.0,
      stockActual: 30,
      stockMinimo: 5,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.M, Talle.L],
      caracteristicas: ['Color azul', 'Manga corta'],
    }),
    new Producto({
      idProducto: 2,
      idProveedor: 102,
      nombre: 'Zapatillas deportivas',
      descripcion: 'Zapatillas cómodas para correr',
      precioVenta: 80.0,
      precioCompra: 50.0,
      stockActual: 15,
      stockMinimo: 3,
      descuentoEfectivo: 0.15,
      descuentoSocios: 0.25,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CALZADO,
      talles: [Talle.XXL, Talle.XL],
      caracteristicas: ['Transpirables', 'Suela antideslizante'],
    }),
    new Producto({
      idProducto: 3,
      idProveedor: 101,
      nombre: 'Buzo con capucha',
      descripcion: 'Buzo de lana suave',
      precioVenta: 60.0,
      precioCompra: 40.0,
      stockActual: 20,
      stockMinimo: 4,
      descuentoEfectivo: 0.05,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.BUZO,
      talles: [Talle.L, Talle.M],
      caracteristicas: ['Disponible en varios colores', 'Lavable a máquina'],
    }),
    new Producto({
      idProducto: 4,
      idProveedor: 103,
      nombre: 'Campera de invierno',
      descripcion: 'Campera térmica para el frío',
      precioVenta: 120.0,
      precioCompra: 80.0,
      stockActual: 10,
      stockMinimo: 2,
      descuentoEfectivo: 0.2,
      descuentoSocios: 0.25,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [Talle.M, Talle.S],
      caracteristicas: ['Resistente al agua', 'Forro polar'],
    }),
    new Producto({
      idProducto: 5,
      idProveedor: 104,
      nombre: 'Camiseta de tirantes',
      descripcion: 'Camiseta liviana para el verano',
      precioVenta: 22.0,
      precioCompra: 12.0,
      stockActual: 40,
      stockMinimo: 8,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.S, Talle.M],
      caracteristicas: ['Ideal para el deporte', 'Rápido secado'],
    }),
    new Producto({
      idProducto: 6,
      idProveedor: 105,
      nombre: 'Botines de fútbol',
      descripcion: 'Botines para campo de fútbol',
      precioVenta: 90.0,
      precioCompra: 60.0,
      stockActual: 12,
      stockMinimo: 2,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CALZADO,
      talles: [Talle.XL, Talle.L],
      caracteristicas: ['Agarre excelente', 'Ligero'],
    }),
    new Producto({
      idProducto: 7,
      idProveedor: 106,
      nombre: 'Short deportivo',
      descripcion: 'Short liviano y cómodo',
      precioVenta: 30.0,
      precioCompra: 20.0,
      stockActual: 25,
      stockMinimo: 5,
      descuentoEfectivo: 0.05,
      descuentoSocios: 0.1,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.M, Talle.L],
      caracteristicas: ['Elástico', 'Transpirable'],
    }),
    new Producto({
      idProducto: 8,
      idProveedor: 107,
      nombre: 'Camiseta estampada',
      descripcion: 'Camiseta con diseño gráfico',
      precioVenta: 28.0,
      precioCompra: 18.0,
      stockActual: 35,
      stockMinimo: 7,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.S, Talle.XS],
      caracteristicas: ['Cotton blend', 'Diseños únicos'],
    }),
    new Producto({
      idProducto: 9,
      idProveedor: 108,
      nombre: 'Pantalones de jogging',
      descripcion: 'Pantalones cómodos para uso diario',
      precioVenta: 55.0,
      precioCompra: 35.0,
      stockActual: 18,
      stockMinimo: 4,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [Talle.M, Talle.L],
      caracteristicas: ['Bolsillos laterales', 'Cintura elástica'],
    }),
    new Producto({
      idProducto: 10,
      idProveedor: 109,
      nombre: 'Gorra deportiva',
      descripcion: 'Gorra ajustable para el sol',
      precioVenta: 15.0,
      precioCompra: 10.0,
      stockActual: 50,
      stockMinimo: 10,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [],
      caracteristicas: ['Transpirable', 'Ligera'],
    }),
    new Producto({
      idProducto: 11,
      idProveedor: 101,
      nombre: 'Pantalones de mezclilla',
      descripcion: 'Pantalones clásicos de mezclilla',
      precioVenta: 45.0,
      precioCompra: 30.0,
      stockActual: 22,
      stockMinimo: 5,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [Talle.M, Talle.L],
      caracteristicas: ['Estilo clásico', 'Duradero'],
    }),
    new Producto({
      idProducto: 12,
      idProveedor: 102,
      nombre: 'Sudadera con cremallera y mas cosas',
      descripcion: 'Sudadera suave y abrigada',
      precioVenta: 70.0,
      precioCompra: 50.0,
      stockActual: 14,
      stockMinimo: 15,
      descuentoEfectivo: 0.2,
      descuentoSocios: 0.25,
      descuentoNoSocios: 0.1,
      categoria: Categoria.BUZO,
      talles: [Talle.L, Talle.M],
      caracteristicas: ['Cremallera completa', 'Capucha ajustable'],
    }),
    new Producto({
      idProducto: 13,
      idProveedor: 103,
      nombre: 'Botas de trekking',
      descripcion: 'Botas resistentes para senderismo',
      precioVenta: 95.0,
      precioCompra: 65.0,
      stockActual: 11,
      stockMinimo: 2,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CALZADO,
      talles: [Talle.XL, Talle.L],
      caracteristicas: ['Impermeables', 'Soporte de tobillo'],
    }),
    new Producto({
      idProducto: 14,
      idProveedor: 104,
      nombre: 'Camiseta de deporte',
      descripcion: 'Camiseta diseñada para el entrenamiento',
      precioVenta: 24.0,
      precioCompra: 15.0,
      stockActual: 45,
      stockMinimo: 10,
      descuentoEfectivo: 0.05,
      descuentoSocios: 0.1,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.M, Talle.L],
      caracteristicas: ['Elástica', 'Secado rápido'],
    }),
    new Producto({
      idProducto: 15,
      idProveedor: 105,
      nombre: 'Chaqueta ligera',
      descripcion: 'Chaqueta ligera para clima templado',
      precioVenta: 85.0,
      precioCompra: 60.0,
      stockActual: 7,
      stockMinimo: 2,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [Talle.M, Talle.S],
      caracteristicas: ['Cortaviento', 'Transpirable'],
    }),
    new Producto({
      idProducto: 16,
      idProveedor: 106,
      nombre: 'Camiseta de algodón',
      descripcion: 'Camiseta de algodón premium',
      precioVenta: 20.0,
      precioCompra: 12.0,
      stockActual: 60,
      stockMinimo: 15,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.S, Talle.M, Talle.L],
      caracteristicas: ['Colores variados', 'Lavable a máquina'],
    }),
    new Producto({
      idProducto: 17,
      idProveedor: 107,
      nombre: 'Bermudas casuales',
      descripcion: 'Bermudas cómodas para el verano',
      precioVenta: 35.0,
      precioCompra: 22.0,
      stockActual: 20,
      stockMinimo: 5,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [Talle.L, Talle.M],
      caracteristicas: ['Ligera', 'Comodidad asegurada'],
    }),
    new Producto({
      idProducto: 18,
      idProveedor: 108,
      nombre: 'Gafas de sol',
      descripcion: 'Gafas UV400',
      precioVenta: 15.0,
      precioCompra: 10.0,
      stockActual: 50,
      stockMinimo: 10,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [],
      caracteristicas: ['Protección UV', 'Diseño moderno'],
    }),
    new Producto({
      idProducto: 19,
      idProveedor: 109,
      nombre: 'Chaqueta de cuero',
      descripcion: 'Chaqueta de cuero auténtico',
      precioVenta: 150.0,
      precioCompra: 100.0,
      stockActual: 8,
      stockMinimo: 2,
      descuentoEfectivo: 0.2,
      descuentoSocios: 0.3,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [Talle.M, Talle.L],
      caracteristicas: ['Estilo elegante', 'Duradero'],
    }),
    new Producto({
      idProducto: 20,
      idProveedor: 101,
      nombre: 'Camisa de vestir',
      descripcion: 'Camisa de algodón de corte clásico',
      precioVenta: 50.0,
      precioCompra: 35.0,
      stockActual: 15,
      stockMinimo: 3,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.L, Talle.M],
      caracteristicas: ['Ideal para ocasiones formales', 'Variedad de colores'],
    }),
    new Producto({
      idProducto: 21,
      idProveedor: 102,
      nombre: 'Cinturón de cuero',
      descripcion: 'Cinturón de cuero genuino',
      precioVenta: 30.0,
      precioCompra: 20.0,
      stockActual: 20,
      stockMinimo: 5,
      descuentoEfectivo: 0.05,
      descuentoSocios: 0.1,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [],
      caracteristicas: ['Ajustable', 'Duradero'],
    }),
    new Producto({
      idProducto: 22,
      idProveedor: 103,
      nombre: 'Botas de invierno',
      descripcion: 'Botas impermeables para clima frío',
      precioVenta: 110.0,
      precioCompra: 75.0,
      stockActual: 6,
      stockMinimo: 2,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CALZADO,
      talles: [Talle.L, Talle.XL],
      caracteristicas: ['Aislantes', 'Comodidad'],
    }),
    new Producto({
      idProducto: 23,
      idProveedor: 104,
      nombre: 'Mochila de trekking',
      descripcion: 'Mochila para excursiones',
      precioVenta: 65.0,
      precioCompra: 45.0,
      stockActual: 10,
      stockMinimo: 3,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.2,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMPERA,
      talles: [],
      caracteristicas: ['Capacidad de 30 litros', 'Resistente al agua'],
    }),
    new Producto({
      idProducto: 24,
      idProveedor: 105,
      nombre: 'Pantalones cortos',
      descripcion: 'Pantalones cortos para climas cálidos',
      precioVenta: 28.0,
      precioCompra: 18.0,
      stockActual: 25,
      stockMinimo: 5,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.S, Talle.M],
      caracteristicas: ['Livianos', 'Secado rápido'],
    }),
    new Producto({
      idProducto: 25,
      idProveedor: 106,
      nombre: 'Camiseta de rayas',
      descripcion: 'Camiseta con diseño a rayas',
      precioVenta: 26.0,
      precioCompra: 16.0,
      stockActual: 32,
      stockMinimo: 8,
      descuentoEfectivo: 0.1,
      descuentoSocios: 0.15,
      descuentoNoSocios: 0.1,
      categoria: Categoria.CAMISETA,
      talles: [Talle.S, Talle.M, Talle.L],
      caracteristicas: ['Material suave', 'Diseño moderno'],
    }),
  ];
}
