name: Image update

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sign-in
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITHUB_TOKEN }} --password-stdin

      - name: Build
        run: docker build . -t ghcr.io/${{ secrets.GITHUB_TOKEN }}/ffc-ecommerce-main:latest

      - name: Push
        run: docker push ghcr.io/${{ secrets.GITHUB_TOKEN }}/ffc-ecommerce-main:latest
