name: Build image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log-in
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build
        run: |
          docker build . -t ghcr.io/${{ github.actor }}/ffc-ecommerce-main:latest \
          --build-arg VITE_PORT=${{ secrets.VITE_PORT }} \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }}

      - name: Push
        run: docker push ghcr.io/${{ github.actor }}/ffc-ecommerce-main:latest
