name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log-in
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/ffc-ecommerce-main:latest

      - name: Push
        run: docker push ghcr.io/${{ github.repository_owner }}/ffc-ecommerce-main:latest
